Create AkhilGKrishnan.md
kautukkundan/Awesome-Profile-README-templates pull request #292
Opened 2020-08-23 16:23 UTC by AkhilGKrishnan

The markdown file must fulfill these conditions:

- [ ] The name of the readme file is your **username.md** if you are making a new creative readme.
- [ ] The name of the readme file is the person's username from where it is inspired from.
- [ ] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

2020-08-24 08:17 UTC, jatin-pahuja requested changes
you forgot the last line

2020-08-24 08:17 UTC, jatin-pahuja commented
this:
The bottom of the readme file contains: ⭐️ From [username](https://github.com/[username])

2020-08-25 08:31 UTC, DeltaCoderr approved these changes

2020-09-10 18:21 UTC, bhaveshlohana approved these changes

2020-10-01 10:23 UTC, merged