Community Guidelines
kautukkundan/Awesome-Profile-README-templates pull request #85
Opened 2020-07-15 21:20 UTC by cristianmarint

This PR adds:

- ✅ Guidelines to Contributing.
- ✅ A better README.
- ✅ GNU GENERAL PUBLIC LICENSE.

2020-07-17 13:23 UTC, ewerton-azevedo approved these changes

2020-07-17 13:27 UTC, ewerton-azevedo requested changes
Hi @cristianmarint I reviewed your changes and I would suggest the following text (not really a big change from what you committed.)

"This repository aims to collect awesome READMEs that developers around the world are using on their profiles to inspire others."  	

What do you think?

2020-07-17 13:27 UTC, ewerton-azevedo approved these changes

2020-07-17 13:28 UTC, ewerton-azevedo approved these changes

2020-07-17 13:36 UTC, cristianmarint commented
> Hi @cristianmarint I reviewed your changes and I would suggest the following text (not really a big change from what you committed.)
> 
> "This repository aims to collect awesome READMEs that developers around the world are using on their profiles to inspire others."
> 
> What do you think?

Hey @ewerton-azevedo thanks for suggesting changes, they where made according.

2020-07-18 09:46 UTC, kautukkundan commented
I'll go through all the changes about community guidelines ASAP.

2020-07-20 09:17 UTC, ewerton-azevedo approved these changes

2026-07-23 02:24 UTC, closed without merging